# Generated by Django 6.0.4 on 2026-06-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_date_range_chunks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='date_range_chunks',
            field=models.PositiveSmallIntegerField(default=4, help_text="Starting number of date-range chunks for the chunked reports (Vendor Payment Activity and Vendor Authorization Accrual Balances). This is a floor: any chunk that approaches Acumen's 150k row export cap is auto-subdivided, so you rarely need to change it."),
        ),
    ]
